# Generated by Django 4.1.4 on 2023-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('href', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('salary', models.CharField(max_length=255, null=True, verbose_name='ЗП')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія')),
                ('recruiter', models.CharField(max_length=255, verbose_name='Рекрутер')),
                ('publication_date', models.CharField(max_length=255, verbose_name='Дата публікації')),
                ('views', models.CharField(max_length=255, verbose_name='Перегляди')),
                ('reviews', models.CharField(max_length=255, verbose_name='Відгуки')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('parse_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
