# Generated by Django 4.1.4 on 2023-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('salary', models.CharField(max_length=50, verbose_name='ЗП')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія')),
                ('recruiter', models.CharField(max_length=255, verbose_name='Рекрутер')),
                ('publication_date', models.CharField(max_length=255, verbose_name='Дата публікації')),
                ('views', models.IntegerField(verbose_name='Перегляди')),
                ('reviews', models.IntegerField(verbose_name='Відгуки')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('additional_info', models.JSONField(verbose_name='Додаткова інформація')),
                ('parse_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
