# Generated by Django 4.1.4 on 2023-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=255, null=True, verbose_name='Компанія'),
        ),
    ]
