# Generated by Django 4.1.4 on 2023-01-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='reviews',
            field=models.CharField(max_length=50, verbose_name='Відгуки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='views',
            field=models.CharField(max_length=50, verbose_name='Перегляди'),
        ),
    ]
